FROM node:19

WORKDIR /app
VOLUME [ "/app" ]

ENV VITE_MOONRAKER_API=http://localhost:7125/
ENV VITE_MOONRAKER_WEBSOCKET=ws://localhost:7125/websocket
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

# CMD npm install && npm run dev
CMD npm run dev