services:
  binfmt:
    image: tonistiigi/binfmt
    container_name: binfmt
    privileged: true
    command: --install arm64,arm
    #network_mode: bridge
    #restart: "no"
  klipper-touch_build_arm32v7:
    build: .
    image: klipper-touch_build_arm32v7
    container_name: klipper-touch_build_arm32v7
    platform: linux/arm/v7
    #user: "1000:1000"
    volumes:
      - ./src-tauri/target/release/bundle/deb/:/app/src-tauri/target/release/bundle/deb/
    depends_on:
      binfmt:
        condition: service_completed_successfully
    #ports:
    #  - '3000:3000'
    # environment:
    #   - VITE_MOONRAKER_API=http://192.168.40.6/
    #   - VITE_MOONRAKER_WEBSOCKET=ws://192.168.40.6/websocket
    #   - HOST=0.0.0.0
    #   - PORT=3000
    # env_file: .env
    #networks:
    #  - front-tier
  klipper-touch_build_arm64v8:
    build: .
    image: klipper-touch_build_arm64v8
    container_name: klipper-touch_build_arm64v8
    platform: linux/arm64/v8
    #user: "1000:1000"
    volumes:
      - ./src-tauri/target/release/bundle/deb/:/app/src-tauri/target/release/bundle/deb/
    depends_on:
      binfmt:
        condition: service_completed_successfully
    #ports:
    #  - '3000:3000'
    # environment:
    #   - VITE_MOONRAKER_API=http://192.168.40.6/
    #   - VITE_MOONRAKER_WEBSOCKET=ws://192.168.40.6/websocket
    #   - HOST=0.0.0.0
    #   - PORT=3000
    # env_file: .env
    #networks:
    #  - front-tier
networks:
  front-tier: {}
