name: 'output-test'

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      package_version: ${{ steps.get_version.outputs.PACKAGE_VERSION }}

    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: get_version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          PACKAGE_VERSION: ${{needs.job1.outputs.package_version}}
        run: echo "$PACKAGE_VERSION"
