name: Raspberry Pi compile
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2.5.2
        id: build_image
        with:
          base_image: dietpi:rpi_armv8_bullseye #https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z
          cpu: cortex-a53
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            apt update -y
            apt install -y ca-certificates curl gnupg
            mkdir -p /etc/apt/keyrings
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
            apt update -y
            apt install -y nodejs libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"            
            npm install
            npm install --save-dev @tauri-apps/cli
            npm run tauri build

      - name: Upload deb bundle
        uses: actions/upload-artifact@v3
        with:
          name: rpi_armv8_bullseye bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/deb/klipper-touch_0.1.0_arm64.deb