name: 'test-upload'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          path: path/to/artifact/world.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            path/to/artifact/world.txt
